version: '3.8'

services:

  backend:
    build: ./backend
    container_name: backend
    environment:
      - ALLOWED_ORIGINS=http://localhost,http://localhost:80
      - AWS_DEFAULT_REGION=us-east-1
      - S3_BUCKET=rapidsummarize-uploads
    volumes:
      - uploads_data:/app/uploads
      - chroma_data:/app/chroma_storage
    ports:
      - "8000:8000"     
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:8000   
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  uploads_data:
  chroma_data: